[package]
name = "axum-keycloak-auth"
version = "0.3.0"
edition = "2021"
rust-version = "1.67.1"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/axum-keycloak-auth"
description = """
Protect axum routes with a JWT emitted by Keycloak.
"""
categories = ["authentication", "web-programming"]
keywords = ["keycloak", "auth", "jwt", "oidc", "axum"]

[dependencies]
axum = "0.7"
futures = "0.3"
http = "1"
jsonwebtoken = "9"
serde = "1"
serde_json = "1"
snafu = "0.7"
time = "0.3"
tower = "0.4"
tracing = "0.1"
typed-builder = "0.18"
